// Alle Texte der Seite. Inhalte: Sascha_Rossi_Website_Inhalte_2026.pdf (DE), EN sinngemäß übersetzt.
export const links = {
  linkedin: 'https://www.linkedin.com/in/sascha-rossi',
  xing: 'https://www.xing.com/profile/Sascha_Rossi',
  email: 's.rossi@flowint.de',
}

// Tech Stack: pro Kategorie zentrale Technologien (core) und ergänzende Erfahrung (extra)
export const techStack = [
  {
    key: 'ai',
    core: ['Claude API', 'OpenAI API', 'Prompt Engineering', 'LLM Integration'],
    extra: ['MCP', 'Structured Outputs', 'AI-assisted Development'],
  },
  {
    key: 'automation',
    core: ['n8n', 'Make', 'REST APIs', 'Webhooks'],
    extra: ['Workflow Automation', 'API Integration'],
  },
  {
    key: 'data',
    core: ['PostgreSQL', 'SQL', 'Apache Airflow', 'ETL/ELT', 'Data Pipelines'],
    extra: ['Datenmodellierung', 'SQL Views'],
  },
  {
    key: 'dev',
    core: ['Python', 'JavaScript', 'PHP', 'WordPress'],
    extra: ['Laravel', 'Vue.js', 'Livewire', 'HTML5', 'Tailwind CSS', 'Jekyll', 'API-basierte Webintegrationen', 'AI-assisted Web Development'],
  },
  {
    key: 'cloud',
    core: ['AWS', 'Docker', 'Linux', 'VPS', 'Self-Hosting'],
    extra: ['AWS S3', 'EC2', 'RDS', 'IAM', 'EBS'],
  },
  {
    key: 'analytics',
    core: ['Power BI', 'Metabase'],
    extra: ['Google Workspace', 'Microsoft 365', 'Meta Graph API', 'Asana', 'KlickTipp', 'Webinargeek', 'Marketing Analytics', 'Tracking', 'Reporting'],
  },
]

export const i18n = {
  de: {
    nav: { about: 'Über mich', work: 'Schwerpunkte', projects: 'Projekte', stack: 'Tech Stack', experience: 'Erfahrung', education: 'Ausbildung', contact: 'Kontakt', menu: 'Menü', close: 'Schließen' },
    hero: {
      eyebrow: 'Hallo, ich bin',
      role: 'Solutions Engineer',
      areas: 'AI Automation · Web Development · Data Engineering',
      claim: 'Web. Automation. Data. AI.',
      text: 'Ich entwickle digitale Lösungen, die Anwendungen, Daten und Geschäftsprozesse miteinander verbinden – von Websites und Webanwendungen über APIs und automatisierte Workflows bis hin zu Datenpipelines, Reporting-Lösungen und AI-gestützten Prozessen.',
      cta: 'Kontakt aufnehmen',
      cta2: 'Mehr erfahren',
      scroll: 'Scrollen',
    },
    about: {
      label: 'Über mich',
      title: 'Technik, die Prozesse wirklich besser macht.',
      paras: [
        'Als Solutions Engineer verbinde ich Software- und Webentwicklung mit Prozessautomatisierung, Data Engineering und modernen AI-Technologien. Mein Schwerpunkt liegt darauf, technische Möglichkeiten in funktionierende, wartbare Lösungen für reale Geschäftsprozesse zu übersetzen.',
        'Mein Hintergrund reicht von Webentwicklung und API-Integration über PostgreSQL, Datenpipelines und Cloud-Infrastruktur bis zu produktiven n8n- und Make-Automatisierungen. AI nutze ich sowohl innerhalb von Anwendungen und Workflows als auch aktiv im Entwicklungsprozess.',
      ],
      connectTitle: 'Was ich verbinde',
      connect: ['Softwareentwicklung', 'Webentwicklung', 'Prozessautomatisierung', 'Data Engineering', 'APIs', 'AI / LLM', 'Cloud-Infrastruktur'],
    },
    background: {
      label: 'Hintergrund',
      title: 'Technisches Know-how trifft auf langjährige operative Erfahrung.',
      paras: [
        'Vor meiner IT-Laufbahn habe ich über viele Jahre in operativen und verantwortlichen Rollen gearbeitet – unter anderem in Teamleitung und Personalverantwortung, Logistik und Transport, Einkauf, Außendienst sowie selbstständig in der Eventbranche.',
        'Diese Erfahrung prägt heute meine technische Arbeit: Ich betrachte Anforderungen nicht nur aus Sicht von Code und Systemen, sondern auch aus Sicht der Menschen, Abläufe und betrieblichen Realität dahinter.',
      ],
      closing: 'Entscheidend ist, ob eine Lösung einen Prozess vereinfacht, zuverlässig funktioniert und einen konkreten geschäftlichen Nutzen schafft.',
    },
    education: {
      label: 'Qualifikationen',
      title: 'Ausbildung & Qualifikationen',
      items: [
        ['2025', 'Fachinformatiker für Anwendungsentwicklung (IHK)', 'GFN Donaueschingen'],
        ['2025', 'Künstliche Intelligenz im Online-Marketing', '121WATT'],
        ['2023', 'EXIN Agile Scrum Foundation', ''],
        ['2019', 'Fachwirt für Logistiksysteme (IHK)', 'Abschluss: sehr gut'],
        ['2014', 'Sachbearbeiter Einkauf', 'Procure Fachverband'],
        ['2011', 'Fachhochschulreife', ''],
        ['2006', 'Ausbildung zum Bürokaufmann', ''],
      ],
    },
    stack: {
      label: 'Fähigkeiten',
      title: 'Tech Stack',
      groups: { ai: 'AI & LLM', automation: 'Automation & Integration', data: 'Data Engineering', dev: 'Development & Web', cloud: 'Cloud & Infrastructure', analytics: 'Analytics & Platforms' },
      extraLabels: { analytics: 'Weitere Plattformen' },
    },
    work: {
      label: 'Fokus',
      title: 'Schwerpunkte',
      items: [
        ['AI & Workflow Automation', 'Produktive Automatisierungen mit n8n, APIs und LLMs, inklusive Trigger-Logik, Datenverarbeitung, Fehlerbehandlung, Validierung und Monitoring.', ['n8n', 'LLMs', 'APIs']],
        ['AI-assisted Web Development', 'Entwicklung von Websites und digitalen Lösungen mit AI-gestützten Entwicklungswerkzeugen sowie Integration von APIs, Automatisierungen und externen Services.', ['WordPress', 'AI-assisted', 'APIs']],
        ['Data Pipelines & Analytics', 'Automatisierte Datenflüsse zwischen Datenquellen, PostgreSQL, Cloud-Infrastruktur und BI-/Reporting-Systemen.', ['PostgreSQL', 'Airflow', 'Power BI']],
        ['API & System Integration', 'Vernetzung von SaaS-, Marketing-, Daten- und Unternehmenssystemen über REST APIs, Webhooks und automatisierte Workflows.', ['REST', 'Webhooks', 'SaaS']],
        ['Cloud & Self-Hosted Infrastructure', 'AWS- sowie Linux-/Docker-basierte Infrastrukturen für Datenverarbeitung, Automatisierung und interne Anwendungen.', ['AWS', 'Docker', 'Linux']],
      ],
    },
    projects: {
      label: 'Fallbeispiele',
      title: 'Ausgewählte Projekte',
      intro: 'Drei produktive Lösungen aus der Praxis und ein eigenständiges Webprojekt.',
      role: 'Data & Automation Engineer',
      principleLabel: 'Engineering-Entscheidung',
      problem: 'Ausgangslage',
      solution: 'Lösung',
      highlights: 'Kernpunkte',
      results: 'Ergebnis',
      flow: 'Datenfluss',
      items: [
        {
          tab: 'Social Moderation',
          title: 'Automatische Moderation von Social-Media-Kommentaren',
          scope: 'Instagram · Facebook',
          principle: 'Deterministische Regeln zuerst, ein LLM nur dort, wo eine semantische Bewertung nötig ist. Nicht jeder Kommentar wird an ein LLM geschickt.',
          problem: 'Kommentare unter Beiträgen sollen zeitnah, freundlich und rechtssicher beantwortet werden. Spam und Beleidigungen sollen verschwinden, sensible Fälle gehören zu einem Menschen.',
          solution: 'Ein n8n-Workflow verarbeitet die Kommentar-Events der Plattformen und entscheidet pro Kommentar: beantworten, löschen, manuell prüfen oder nur protokollieren.',
          points: [
            'Harte Regeln fangen Spam, Beleidigungen und sensible Fälle vor dem LLM ab. Das Ergebnis des LLM wird vor dem Absenden gegen Sicherheits- und Plausibilitätsregeln validiert.',
            'Korrekturen wirken ohne neuen Deploy: Ein Abgleich gegen eine Korrektur-Tabelle (Textmuster und Embedding-Ähnlichkeit) übersteuert das LLM.',
            'Sensible Fälle bekommen keine Auto-Antwort, sondern gehen per E-Mail an eine Person.',
            'Bei klarem Kontaktwunsch geht optional eine Direktnachricht raus, im zulässigen Zeitfenster.',
            'Jeder Vorgang wird nachvollziehbar protokolliert.',
          ],
          tags: ['n8n', 'LLM', 'Embeddings', 'Meta Graph API', 'Google Sheets'],
          metrics: [['> 1.000', 'Kommentare pro Woche'], ['≈ 25 h', 'Zeitersparnis pro Woche'], ['≈ 75 %', 'automatisiert, Rest manuell geprüft']],
          results: [
            'Deutlich weniger sichtbarer Spam unter den Beiträgen.',
            'Was nach den Vorgaben im LLM-Prompt nicht automatisch beantwortet werden soll, geht zur manuellen Prüfung an eine Person.',
            'Rund vier Versionen entwickelt, stabil im Produktivbetrieb.',
          ],
          flow: [
            [['Kommentar', 'Instagram / Facebook']],
            [['Vorfilter', 'Eigene Kommentare, Dubletten']],
            [['Regeln + LLM', 'Klassifizierung']],
            [['Validierung', 'Entscheidung']],
            [['Antworten'], ['Löschen'], ['Manuelle Prüfung'], ['Nur protokollieren']],
            [['Protokoll', 'Tabelle']],
          ],
        },
        {
          tab: 'Booking Workflow',
          title: 'Buchungs-Workflow für Drehtermine',
          scope: 'Internes Social-Media-Team',
          problem: 'Anfragen für Drehtermine sollen strukturiert erfasst, freigegeben und automatisch in Kalender und Übersicht übernommen werden, mit sparsamem Umgang mit personenbezogenen Daten.',
          solution: 'Ein Webformular sendet die Anfrage an n8n. Ein Workflow legt sie in Aufgabenverwaltung und Datenbank ab. Nach der Freigabe erzeugt ein zweiter Workflow Kalendereintrag und Übersicht.',
          points: [
            'Webformular als Einstieg: Die Anfrage geht per Webhook an n8n, eine Eingangsbestätigung folgt automatisch.',
            'Datenschutz und Datenminimierung: Die Aufgabenverwaltung enthält nur einen reduzierten Datensatz, die vollständigen personenbezogenen Daten liegen in der PostgreSQL-Datenbank.',
            'Freigabeprozess: Erst nach der Freigabe entsteht der Termin. Zwei getrennte Workflows für Eingang und Freigabe.',
            'Kalenderintegration: Bestätigte Termine landen automatisch im gemeinsamen Kalender, eine Übersicht wird fortlaufend ergänzt.',
            'Technische Dokumentation für IT-Betrieb und Datenschutzbeauftragte.',
          ],
          tags: ['n8n', 'PostgreSQL', 'AWS', 'Webhooks', 'Asana', 'Outlook Kalender', 'Google Sheets'],
          metrics: [['30', 'Nutzer'], ['≈ 5 h', 'Zeitersparnis pro Woche'], ['0', 'Terminkollisionen']],
          results: [
            'Vorher lief viel über mündliche Abstimmung, jetzt ist alles transparent und verbindlich.',
            'Terminkollisionen werden vermieden.',
          ],
          flow: [
            [['Webformular']],
            [['Workflow 1', 'Eingang und Prüfung']],
            [['Aufgabe', 'reduzierte Daten'], ['Datenbank', 'vollständige Daten']],
            [['Freigabe']],
            [['Workflow 2', 'nach Freigabe']],
            [['Kalender'], ['Übersicht']],
          ],
        },
        {
          tab: 'Data Pipeline',
          title: 'Tägliche Kontakt-Synchronisierung ins Newsletter-System',
          scope: '6 Standorte',
          problem: 'Kontakte aus mehreren Standort-Systemen sollen automatisch, sicher und dubletten-frei im Newsletter-System ankommen. Abgemeldete Personen müssen dauerhaft ausgeschlossen bleiben.',
          solution: 'Ein nächtlicher Ablauf importiert die Kontakte je Standort, konsolidiert sie in einer PostgreSQL-Datenbank, filtert Abmeldungen, verschlüsselt den Export und übergibt ihn über einen Cloud-Speicher an einen n8n-Workflow.',
          points: [
            'Mehrere Standortsysteme werden zu einem gemeinsamen Bestand konsolidiert, dedupliziert per SQL.',
            'Autokorrektur von Tippfehlern bei bekannten E-Mail-Anbietern.',
            'Sperrliste: Abmeldungen werden bei jedem Lauf durchgesetzt.',
            'Verschlüsselter Transfer mit automatischer Löschfrist.',
            'Fehlerreporting per E-Mail.',
          ],
          tags: ['PostgreSQL', 'SQL', 'ETL', 'GPG', 'AWS S3', 'n8n', 'KlickTipp'],
          metrics: [['150–200', 'Kontakte pro Tag'], ['6', 'Standorte'], ['0', 'neue Duplikate']],
          results: [
            'Der manuelle Pflegeaufwand entfällt, und viele Fehlerquellen sind beseitigt.',
            'Eine Autokorrektur behebt Tippfehler bei bekannten E-Mail-Anbietern.',
            'Der Datenbestand für den Newsletter ist immer aktuell und wächst dauerhaft.',
          ],
          flow: [
            [['Standort-Systeme', '6 Standorte']],
            [['Konsolidierung', 'PostgreSQL, Opt-out-Filter']],
            [['Export', 'verschlüsselt']],
            [['Cloud-Speicher', 'Löschfrist']],
            [['n8n']],
            [['Newsletter-System']],
          ],
        },
        {
          tab: 'DJ Website',
          title: 'DJ De la Rossi – Künstlerwebsite',
          scope: 'Web Development · Eigenprojekt',
          role: 'Web Development · AI-assisted Development',
          labels: { problem: 'Ausgangslage', solution: 'Umsetzung', highlights: 'Schwerpunkte' },
          problem: 'Für meine Tätigkeit als DJ sollte eine eigenständige Künstlerwebsite entstehen, die Musik, Auftritte, Informationen und Kontaktmöglichkeiten in einem modernen digitalen Auftritt verbindet.',
          solution: 'Konzeption und Entwicklung einer responsiven Website mit individuellem Dark-Design, dynamischen UI-Elementen und strukturierter Inhaltsarchitektur. Die Umsetzung kombiniert klassische Webtechnologien mit AI-assisted Development.',
          points: [
            'Responsives Design für Desktop, Tablet und Mobile',
            'Individuelles visuelles Erscheinungsbild passend zur Künstleridentität',
            'Dynamische und animierte UI-Elemente',
            'Strukturierte Darstellung von Musik, Auftritten und Künstlerprofil',
            'Direkte Kontakt- und Social-Media-Verknüpfungen',
            'AI-assisted Development als Bestandteil des Entwicklungsprozesses',
          ],
          tags: ['HTML5', 'CSS3', 'Vanilla JavaScript', 'JSON-LD / Schema.org', 'AI-assisted Development'],
          link: { label: 'Website ansehen ↗', url: 'https://www.delarossi.de/' },
        },
      ],
    },
    experience: {
      label: 'Werdegang',
      title: 'Erfahrung',
      items: [
        ['08/2026 – heute', 'Solutions Engineer', 'Reknova GmbH', 'Webentwicklung und WordPress sind ein wesentlicher Teil meiner Arbeit. Dazu kommen AI-assisted Development, die Automatisierung von Marketing- und Geschäftsprozessen, Entwicklung und Integration von APIs, systemübergreifende Workflows, Reporting- und Analyse-Lösungen sowie die Integration von AI-/LLM-Komponenten. Technische Umsetzung von der Anforderungsanalyse über Entwicklung und Testing bis zur Integration.', ['Webentwicklung', 'WordPress', 'AI-assisted Development', 'APIs', 'Workflows', 'Reporting', 'LLM-Integration']],
        ['02/2025 – 07/2026', 'Data & Automation Engineer', 'MVZ Dr. Dr. Dorow GmbH', 'Entwicklung produktiver n8n- und Make-Workflows, API-Integrationen, PostgreSQL und Datenverarbeitung, Python-/Airflow-Datenpipelines, AWS-Infrastruktur, AI-gestützte Automatisierungen, Marketing- und Tracking-Analysen sowie Dashboards mit Power BI und Metabase. Zusätzlich Administration und Dokumentation der Marketing-IT.', ['n8n', 'Make', 'PostgreSQL', 'Python', 'Airflow', 'AWS', 'Power BI', 'Metabase']],
        ['05/2024 – 01/2025', 'Webentwickler (Praktikum)', 'Bitblades Solutions UG / Chaingateway', 'Backend mit PHP/Laravel, Frontend mit JavaScript, Vue.js und Livewire, Tailwind CSS, relationale Datenbanken, Redis, WebSockets und Jekyll. Mitarbeit an der Architektur eines Softwareprodukts.', ['PHP / Laravel', 'JavaScript', 'Vue.js', 'Livewire', 'Tailwind CSS', 'Redis', 'WebSockets', 'Jekyll']],
      ],
      earlierTitle: 'Frühere Erfahrung',
      earlierIntro: 'Vor meiner IT-Laufbahn habe ich bereits umfangreiche Berufserfahrung gesammelt. Sie ergänzt meinen technischen Hintergrund um ein Verständnis realer Geschäftsprozesse.',
      earlierItems: ['Teamleitung und Personalverantwortung', 'Freelancer in der Eventbranche', 'Teamleitung Logistik / Transport', 'Technischer Einkauf und Außendienst'],
      earlierLinksTitle: 'Was ich daraus in die Technik mitbringe',
      earlierLinks: ['Prozessverständnis', 'Kundenorientierung', 'Organisation', 'Kommunikation', 'Verantwortung', 'Verständnis realer Geschäftsprozesse'],
    },
    contact: {
      label: 'Kontakt',
      title: 'Lass uns über die passende Zusammenarbeit sprechen.',
      text: 'Ob als Verstärkung für dein Team oder für einzelne Projekte.',
      mail: 'E-Mail schreiben',
    },
    footer: 'Sascha Rossi · Solutions Engineer',
    langLabel: 'Sprache',
    legal: {
      back: '← Zurück zur Startseite',
      impressum: {
        title: 'Impressum',
        blocks: [
          ['Angaben gemäß § 5 DDG', ['Sascha Rossi', 'Bahnhofstr. 28', '79848 Bonndorf im Schwarzwald', 'Deutschland']],
          ['Kontakt', ['E-Mail: s.rossi@flowint.de']],
          ['Umsatzsteuer', ['Kleinunternehmer im Sinne von § 19 UStG. Es wird keine Umsatzsteuer ausgewiesen.']],
          ['Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV', ['Sascha Rossi, Anschrift wie oben']],
          ['Haftung für Inhalte', ['Als Diensteanbieter bin ich nach den allgemeinen Gesetzen für eigene Inhalte auf diesen Seiten verantwortlich. Nach §§ 8 bis 10 DDG bin ich jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Bei Bekanntwerden entsprechender Rechtsverletzungen entferne ich diese Inhalte umgehend.']],
          ['Haftung für Links', ['Diese Seite enthält Links zu externen Websites Dritter (LinkedIn, XING), auf deren Inhalte ich keinen Einfluss habe. Für diese fremden Inhalte kann ich keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter verantwortlich.']],
        ],
      },
      datenschutz: {
        title: 'Datenschutzerklärung',
        blocks: [
          ['1. Verantwortlicher', ['Sascha Rossi, Bahnhofstr. 28, 79848 Bonndorf im Schwarzwald, Deutschland', 'E-Mail: s.rossi@flowint.de']],
          ['2. Hosting über GitHub Pages', ['Diese Website wird über GitHub Pages betrieben. Anbieter ist die GitHub Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. Beim Aufruf der Seite verarbeitet der Anbieter technisch notwendige Daten in Server-Logfiles, insbesondere die IP-Adresse, Datum und Uhrzeit des Zugriffs, die aufgerufene Seite sowie Browser- und Systeminformationen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an einer sicheren und stabilen Bereitstellung der Website).', 'Dabei kann eine Übermittlung von Daten in die USA stattfinden. Die Übermittlung stützt sich auf den Angemessenheitsbeschluss der EU-Kommission (EU-US Data Privacy Framework) bzw. auf Standardvertragsklauseln.']],
          ['3. Keine Cookies, kein Tracking', ['Diese Website setzt keine Cookies und verwendet keine Analyse- oder Tracking-Werkzeuge. Schriftarten werden lokal von dieser Website ausgeliefert, es werden keine Daten an Google oder andere Schriftanbieter übertragen.', 'Die gewählte Sprache (Deutsch/Englisch) wird ausschließlich im lokalen Speicher deines Browsers abgelegt, damit sie beim nächsten Besuch erhalten bleibt. Diese Information wird nicht an mich oder Dritte übertragen und enthält keine personenbezogenen Daten.']],
          ['4. Externe Links', ['Die Website verlinkt auf LinkedIn und XING. Erst wenn du einen dieser Links anklickst, werden Daten an den jeweiligen Anbieter übertragen. Für die Datenverarbeitung dort gelten die Datenschutzerklärungen der Anbieter.']],
          ['5. Kontaktaufnahme per E-Mail', ['Wenn du mir eine E-Mail schreibst, verarbeite ich deine Angaben (E-Mail-Adresse, Inhalt der Nachricht) zur Bearbeitung deiner Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b bzw. lit. f DSGVO. Die Daten werden gelöscht, sobald sie für den Zweck nicht mehr erforderlich sind und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.']],
          ['6. Deine Rechte', ['Du hast das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) und Widerspruch (Art. 21). Wende dich dafür an die oben genannte E-Mail-Adresse.', 'Außerdem hast du das Recht, dich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Zuständig ist der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg, Lautenschlagerstraße 20, 70173 Stuttgart.']],
          ['Stand', ['September 2026']],
        ],
      },
    },
    footerLinks: { impressum: 'Impressum', datenschutz: 'Datenschutz' },
  },
  en: {
    nav: { about: 'About', work: 'Focus Areas', projects: 'Projects', stack: 'Tech Stack', experience: 'Experience', education: 'Education', contact: 'Contact', menu: 'Menu', close: 'Close' },
    hero: {
      eyebrow: "Hi, I'm",
      role: 'Solutions Engineer',
      areas: 'AI Automation · Web Development · Data Engineering',
      claim: 'Web. Automation. Data. AI.',
      text: 'I build digital solutions that connect applications, data and business processes – from websites and web applications to APIs and automated workflows, data pipelines, reporting solutions and AI-powered processes.',
      cta: 'Get in touch',
      cta2: 'Learn more',
      scroll: 'Scroll',
    },
    about: {
      label: 'About',
      title: 'Technology that actually improves processes.',
      paras: [
        'As a Solutions Engineer, I combine software and web development with process automation, data engineering and modern AI technologies. My focus is on turning technical possibilities into working, maintainable solutions for real business processes.',
        'My background ranges from web development and API integration to PostgreSQL, data pipelines and cloud infrastructure, through to production n8n and Make automations. I use AI both inside applications and workflows and actively as part of the development process.',
      ],
      connectTitle: 'What I connect',
      connect: ['Software development', 'Web development', 'Process automation', 'Data engineering', 'APIs', 'AI / LLM', 'Cloud infrastructure'],
    },
    background: {
      label: 'Background',
      title: 'Technical know-how meets years of operational experience.',
      paras: [
        'Before my IT career I worked for many years in operational and leadership roles – including team leadership and staff responsibility, logistics and transport, purchasing, field sales, and self-employed in the event industry.',
        'This experience shapes my technical work today: I look at requirements not only from the perspective of code and systems, but also from the perspective of the people, workflows and operational reality behind them.',
      ],
      closing: 'What matters is whether a solution simplifies a process, works reliably and delivers concrete business value.',
    },
    education: {
      label: 'Qualifications',
      title: 'Education & Qualifications',
      items: [
        ['2025', 'IT Specialist for Application Development (IHK)', 'GFN Donaueschingen'],
        ['2025', 'Artificial Intelligence in Online Marketing', '121WATT'],
        ['2023', 'EXIN Agile Scrum Foundation', ''],
        ['2019', 'Certified Logistics Systems Specialist (IHK)', 'Grade: very good'],
        ['2014', 'Purchasing Clerk', 'Procure Fachverband'],
        ['2011', 'Advanced Technical College Entrance Qualification (Fachhochschulreife)', ''],
        ['2006', 'Apprenticeship as Office Clerk (Bürokaufmann)', ''],
      ],
    },
    stack: {
      label: 'Capabilities',
      title: 'Tech Stack',
      groups: { ai: 'AI & LLM', automation: 'Automation & Integration', data: 'Data Engineering', dev: 'Development & Web', cloud: 'Cloud & Infrastructure', analytics: 'Analytics & Platforms' },
      extraLabels: { analytics: 'Further platforms' },
      rename: { Datenmodellierung: 'Data Modelling' },
    },
    work: {
      label: 'Focus',
      title: 'Focus Areas',
      items: [
        ['AI & Workflow Automation', 'Production automations with n8n, APIs and LLMs, including trigger logic, data processing, error handling, validation and monitoring.', ['n8n', 'LLMs', 'APIs']],
        ['AI-assisted Web Development', 'Building websites and digital solutions with AI-assisted development tools, plus integration of APIs, automations and external services.', ['WordPress', 'AI-assisted', 'APIs']],
        ['Data Pipelines & Analytics', 'Automated data flows between data sources, PostgreSQL, cloud infrastructure and BI/reporting systems.', ['PostgreSQL', 'Airflow', 'Power BI']],
        ['API & System Integration', 'Connecting SaaS, marketing, data and enterprise systems via REST APIs, webhooks and automated workflows.', ['REST', 'Webhooks', 'SaaS']],
        ['Cloud & Self-Hosted Infrastructure', 'AWS and Linux/Docker-based infrastructure for data processing, automation and internal applications.', ['AWS', 'Docker', 'Linux']],
      ],
    },
    projects: {
      label: 'Case studies',
      title: 'Selected Projects',
      intro: 'Three production solutions from real-world practice and one independent web project.',
      role: 'Data & Automation Engineer',
      principleLabel: 'Engineering decision',
      problem: 'Starting point',
      solution: 'Solution',
      highlights: 'Key points',
      results: 'Results',
      flow: 'Data flow',
      items: [
        {
          tab: 'Social Moderation',
          title: 'Automated Social Media Comment Moderation',
          scope: 'Instagram · Facebook',
          principle: 'Deterministic rules first, an LLM only where a semantic assessment is needed. Not every comment is sent to an LLM.',
          problem: 'Comments under posts need to be answered quickly, in a friendly tone and in compliance with regulations. Spam and insults should disappear, and sensitive cases belong with a person.',
          solution: 'An n8n workflow processes the platforms’ comment events and decides for each comment: reply, delete, send to manual review or just log.',
          points: [
            'Hard rules catch spam, insults and sensitive cases before the LLM. The LLM result is validated against safety and plausibility rules before anything is sent.',
            'Corrections take effect without a new deployment: a comparison against a corrections table (text patterns and embedding similarity) overrides the LLM.',
            'Sensitive cases get no auto-reply and go to a person by email instead.',
            'For a clear request to be contacted, an optional direct message is sent within the permitted time window.',
            'Every action is logged traceably.',
          ],
          tags: ['n8n', 'LLM', 'Embeddings', 'Meta Graph API', 'Google Sheets'],
          metrics: [['> 1,000', 'comments per week'], ['≈ 25 h', 'time saved per week'], ['≈ 75 %', 'automated, rest manually reviewed']],
          results: [
            'Noticeably less visible spam under the posts.',
            'Anything that the LLM instructions say should not be answered automatically goes to a person for manual review.',
            'About four versions built, stable in production.',
          ],
          flow: [
            [['Comment', 'Instagram / Facebook']],
            [['Pre-filter', 'Own comments, duplicates']],
            [['Rules + LLM', 'Classification']],
            [['Validation', 'Decision']],
            [['Reply'], ['Delete'], ['Manual review'], ['Log only']],
            [['Log', 'Spreadsheet']],
          ],
        },
        {
          tab: 'Booking Workflow',
          title: 'Booking Workflow for Video Shoots',
          scope: 'Internal social media team',
          problem: 'Requests for video shoots should be captured in a structured way, approved and automatically transferred to the calendar and overview, with minimal handling of personal data.',
          solution: 'A web form sends the request to n8n. One workflow stores it in the task tool and the database. After approval, a second workflow creates the calendar entry and overview.',
          points: [
            'Web form as entry point: the request goes to n8n via webhook, a confirmation of receipt follows automatically.',
            'Data protection and minimisation: the task tool holds only a reduced record, the full personal data lives in the PostgreSQL database.',
            'Approval process: the appointment is only created after approval. Two separate workflows for intake and approval.',
            'Calendar integration: confirmed appointments land in the shared calendar automatically, an overview is kept up to date.',
            'Technical documentation for IT operations and the data protection officer.',
          ],
          tags: ['n8n', 'PostgreSQL', 'AWS', 'Webhooks', 'Asana', 'Outlook Kalender', 'Google Sheets'],
          metrics: [['30', 'users'], ['≈ 5 h', 'time saved per week'], ['0', 'scheduling conflicts']],
          results: [
            'Previously a lot was coordinated verbally, now everything is transparent and binding.',
            'Scheduling conflicts are avoided.',
          ],
          flow: [
            [['Web form']],
            [['Workflow 1', 'Intake and checks']],
            [['Task', 'reduced data'], ['Database', 'full data']],
            [['Approval']],
            [['Workflow 2', 'after approval']],
            [['Calendar'], ['Overview']],
          ],
        },
        {
          tab: 'Data Pipeline',
          title: 'Daily Contact Sync to the Newsletter System',
          scope: '6 locations',
          problem: 'Contacts from several location systems should arrive in the newsletter system automatically, securely and without duplicates. Unsubscribed people must stay permanently excluded.',
          solution: 'A nightly run imports the contacts per location, consolidates them in a PostgreSQL database, filters out unsubscribes, encrypts the export and hands it over via cloud storage to an n8n workflow.',
          points: [
            'Several location systems are consolidated into one shared dataset, deduplicated in SQL.',
            'Auto-correction of typos in well-known email providers.',
            'Block list: unsubscribes are enforced on every run.',
            'Encrypted transfer with an automatic deletion period.',
            'Error reporting by email.',
          ],
          tags: ['PostgreSQL', 'SQL', 'ETL', 'GPG', 'AWS S3', 'n8n', 'KlickTipp'],
          metrics: [['150–200', 'contacts per day'], ['6', 'locations'], ['0', 'new duplicates']],
          results: [
            'Manual maintenance is gone and many sources of error are eliminated.',
            'An auto-correction fixes typos in well-known email providers.',
            'The newsletter database is always up to date and keeps growing.',
          ],
          flow: [
            [['Location systems', '6 locations']],
            [['Consolidation', 'PostgreSQL, opt-out filter']],
            [['Export', 'encrypted']],
            [['Cloud storage', 'retention limit']],
            [['n8n']],
            [['Newsletter system']],
          ],
        },
        {
          tab: 'DJ Website',
          title: 'DJ De la Rossi – Artist Website',
          scope: 'Web Development · Personal Project',
          role: 'Web Development · AI-assisted Development',
          labels: { problem: 'Challenge', solution: 'Implementation', highlights: 'Key points' },
          problem: 'Create a dedicated artist website for my work as a DJ, combining music, events, information and contact options in a modern digital presence.',
          solution: 'Design and development of a responsive website with an individual dark visual style, dynamic UI elements and a structured content architecture. The implementation combines classic web technologies with AI-assisted development.',
          points: [
            'Responsive design for desktop, tablet and mobile',
            'Individual visual identity aligned with the artist brand',
            'Dynamic and animated UI elements',
            'Structured presentation of music, events and artist information',
            'Direct contact and social-media links',
            'AI-assisted development as part of the development workflow',
          ],
          tags: ['HTML5', 'CSS3', 'Vanilla JavaScript', 'JSON-LD / Schema.org', 'AI-assisted Development'],
          link: { label: 'View website ↗', url: 'https://www.delarossi.de/' },
        },
      ],
    },
    experience: {
      label: 'Career',
      title: 'Experience',
      items: [
        ['08/2026 – present', 'Solutions Engineer', 'Reknova GmbH', 'Web development and WordPress are a substantial part of my work. On top of that come AI-assisted development, automation of marketing and business processes, development and integration of APIs, cross-system workflows, reporting and analytics solutions, and integration of AI/LLM components. Technical delivery from requirements analysis through development and testing to integration.', ['Web development', 'WordPress', 'AI-assisted development', 'APIs', 'Workflows', 'Reporting', 'LLM integration']],
        ['02/2025 – 07/2026', 'Data & Automation Engineer', 'MVZ Dr. Dr. Dorow GmbH', 'Development of production n8n and Make workflows, API integrations, PostgreSQL and data processing, Python/Airflow data pipelines, AWS infrastructure, AI-powered automations, marketing and tracking analyses, and dashboards with Power BI and Metabase. Additionally administration and documentation of marketing IT.', ['n8n', 'Make', 'PostgreSQL', 'Python', 'Airflow', 'AWS', 'Power BI', 'Metabase']],
        ['05/2024 – 01/2025', 'Web Developer (Internship)', 'Bitblades Solutions UG / Chaingateway', 'Backend with PHP/Laravel, frontend with JavaScript, Vue.js and Livewire, Tailwind CSS, relational databases, Redis, WebSockets and Jekyll. Contributed to the architecture of a software product.', ['PHP / Laravel', 'JavaScript', 'Vue.js', 'Livewire', 'Tailwind CSS', 'Redis', 'WebSockets', 'Jekyll']],
      ],
      earlierTitle: 'Earlier experience',
      earlierIntro: 'Before my IT career I gained substantial professional experience. It adds an understanding of real business processes to my technical background.',
      earlierItems: ['Team leadership and staff responsibility', 'Freelancer in the event industry', 'Team lead logistics / transport', 'Technical purchasing and field sales'],
      earlierLinksTitle: 'What I bring from it into technology',
      earlierLinks: ['Process understanding', 'Customer orientation', 'Organisation', 'Communication', 'Responsibility', 'Understanding of real business processes'],
    },
    contact: {
      label: 'Contact',
      title: "Let's talk about the right way to work together.",
      text: 'Whether as a reinforcement for your team or for individual projects.',
      mail: 'Send an email',
    },
    footer: 'Sascha Rossi · Solutions Engineer',
    langLabel: 'Language',
    legal: {
      back: '← Back to home',
      impressum: {
        title: 'Legal Notice',
        blocks: [
          ['Information pursuant to § 5 DDG', ['Sascha Rossi', 'Bahnhofstr. 28', '79848 Bonndorf im Schwarzwald', 'Germany']],
          ['Contact', ['Email: s.rossi@flowint.de']],
          ['Value added tax', ['Small business owner within the meaning of § 19 UStG. No VAT is charged.']],
          ['Responsible for content under § 18 (2) MStV', ['Sascha Rossi, address as above']],
          ['Liability for content', ['As a service provider, I am responsible for my own content on these pages under the general laws. Under §§ 8 to 10 DDG, however, I am not obliged to monitor transmitted or stored third-party information or to investigate circumstances that indicate unlawful activity. Once I become aware of such infringements, I will remove the content immediately.']],
          ['Liability for links', ['This site contains links to external third-party websites (LinkedIn, XING) over whose content I have no influence. I cannot accept any liability for this third-party content. The respective provider is always responsible for the content of the linked pages.']],
        ],
      },
      datenschutz: {
        title: 'Privacy Policy',
        blocks: [
          ['1. Controller', ['Sascha Rossi, Bahnhofstr. 28, 79848 Bonndorf im Schwarzwald, Germany', 'Email: s.rossi@flowint.de']],
          ['2. Hosting via GitHub Pages', ['This website is hosted on GitHub Pages, provided by GitHub Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. When you visit the site, the provider processes technically necessary data in server log files, in particular your IP address, date and time of access, the page requested and browser and system information. The legal basis is Art. 6 (1) (f) GDPR (legitimate interest in providing the website securely and reliably).', 'Data may be transferred to the USA. The transfer relies on the European Commission’s adequacy decision (EU-US Data Privacy Framework) or standard contractual clauses.']],
          ['3. No cookies, no tracking', ['This website does not set cookies and does not use analytics or tracking tools. Fonts are served locally from this website; no data is sent to Google or other font providers.', 'Your chosen language (German/English) is stored only in your browser’s local storage so that it is remembered on your next visit. This information is not transmitted to me or to third parties and contains no personal data.']],
          ['4. External links', ['This website links to LinkedIn and XING. Data is only transferred to the respective provider once you click one of these links. The providers’ own privacy policies apply to processing there.']],
          ['5. Contact by email', ['If you email me, I process your details (email address, message content) to handle your request. The legal basis is Art. 6 (1) (b) or (f) GDPR. The data is deleted once it is no longer needed for its purpose and no statutory retention duties apply.']],
          ['6. Your rights', ['You have the right of access (Art. 15 GDPR), rectification (Art. 16), erasure (Art. 17), restriction of processing (Art. 18), data portability (Art. 20) and objection (Art. 21). Please contact me at the email address above.', 'You also have the right to lodge a complaint with a data protection supervisory authority. The competent authority is the State Commissioner for Data Protection and Freedom of Information Baden-Württemberg (LfDI), Lautenschlagerstraße 20, 70173 Stuttgart, Germany.']],
          ['Last updated', ['September 2026']],
        ],
      },
    },
    footerLinks: { impressum: 'Legal Notice', datenschutz: 'Privacy Policy' },
  },
}
